using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using TheAirline.Model.GeneralModel;

namespace TheAirline.Model.AirlinerModel
{
    //the contract for an airline for a manufacturer
    [Serializable]
    public class ManufacturerContract : ISerializable
    {
        #region Constructors and Destructors

        public ManufacturerContract(Manufacturer manufacturer, DateTime date, int length, double discount)
        {
            Manufacturer = manufacturer;
            Airliners = length;
            SigningDate = date;
            Length = length;
            Discount = discount;
            ExpireDate = date.AddYears(Length);
            PurchasedAirliners = 0;
        }

        //returns the termination fee for the contract

        private ManufacturerContract(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop.Name.ToLower() == "manufacturer")
                    {
                        string manufacturer = ((Manufacturer) entry.Value).Name;
                        Manufacturer = Manufacturers.GetManufacturer(manufacturer);
                    }
                    else
                    {
                        if (prop is FieldInfo)
                        {
                            ((FieldInfo) prop).SetValue(this, entry.Value);
                        }
                        else
                        {
                            ((PropertyInfo) prop).SetValue(this, entry.Value);
                        }
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning) notSet.GetCustomAttribute(typeof (Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Public Properties

        [Versioning("airliners")]
        public int Airliners { get; set; }

        [Versioning("discount")]
        public double Discount { get; set; }

        [Versioning("expiredate")]
        public DateTime ExpireDate { get; set; }

        [Versioning("length")]
        public int Length { get; set; }

        [Versioning("manufacturer")]
        public Manufacturer Manufacturer { get; set; }

        [Versioning("purchasedairliners")]
        public int PurchasedAirliners { get; set; }

        [Versioning("signingdate")]
        public DateTime SigningDate { get; set; }

        #endregion

        #region Public Methods and Operators

        public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                      .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                          .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo) member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo) member).GetValue(this, null);
                }

                var att = (Versioning) member.GetCustomAttribute(typeof (Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        public double GetDiscount(int airliners)
        {
            airliners = PurchasedAirliners;
            if (Length <= 3)
            {
                Discount = (PurchasedAirliners/2) + 1;
            }
            else if (Length <= 5)
            {
                Discount = (PurchasedAirliners/2) + 2;
            }
            else if (Length <= 7)
            {
                Discount = (PurchasedAirliners/2) + 4;
            }
            else if (Length <= 15)
            {
                Discount = (PurchasedAirliners/2) + 7;
            }
            else
            {
                Discount = 1;
            }

            return Discount;
        }

        public double GetTerminationFee()
        {
            return GeneralHelpers.GetInflationPrice(Length*1000000);
        }

        #endregion
    }
}