namespace TheAirline.Model.GeneralModel.StatisticsModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Runtime.Serialization;

    //the class for general statistics
    [Serializable]
    public class GeneralStatistics : ISerializable
    {
        #region Constructors and Destructors

        public GeneralStatistics()
        {
            this.StatValues = new List<StatisticsValue>();
        }

        private GeneralStatistics(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                this.GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    this.GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop is FieldInfo)
                    {
                        ((FieldInfo)prop).SetValue(this, entry.Value);
                    }
                    else
                    {
                        ((PropertyInfo)prop).SetValue(this, entry.Value);
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning)notSet.GetCustomAttribute(typeof(Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Public Properties

        [Versioning("values")]
        public List<StatisticsValue> StatValues { get; set; }

        #endregion

        #region Public Methods and Operators

        public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = this.GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo)member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo)member).GetValue(this, null);
                }

                var att = (Versioning)member.GetCustomAttribute(typeof(Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        public void addStatisticsValue(int year, StatisticsType type, double value)
        {
            lock (this.StatValues)
            {
                StatisticsValue item = this.StatValues.Find(s => s.Year == year && s.Stat.Shortname == type.Shortname);

                if (item == null)
                {
                    this.StatValues.Add(new StatisticsValue(year, type, value));
                }
                else
                {
                    item.Value += value;
                }
            }
        }

        public void clear()
        {
          
            lock (this.StatValues)
            {
                this.StatValues.Clear();
            }
        }

        //returns the value for a statistics type for a year
        public double getStatisticsValue(int year, StatisticsType type)
        {
            StatisticsValue item;
            lock (this.StatValues)
            {
                var stats = new List<StatisticsValue>(this.StatValues); 

                item =
                    stats.FirstOrDefault(s => s.Stat != null && s.Year == year && s.Stat.Shortname == type.Shortname);

            }
            if (item == null)
            {
                return 0;
            }
            return item.Value;
        }

        //returns the total value for a statistics type
        public double getStatisticsValue(StatisticsType type)
        {
            double sum = 0;
            lock (this.StatValues)
            {
                if (this.StatValues != null
                    && this.StatValues.Exists(s => s.Stat != null && s.Stat.Shortname == type.Shortname))
                {
                    sum = this.StatValues.Where(s => s.Stat != null && s.Stat.Shortname == type.Shortname)
                        .Sum(s => s.Value);
                }
            }
            return sum;
        }

        //adds the value for a statistics type for a year

        //returns all years with statistics
        public List<int> getYears()
        {
            List<int> years = new List<int>();
            
            lock (this.StatValues)
                years = this.StatValues.Select(s => s.Year).Distinct().ToList();

            return years;
        }

        public void setStatisticsValue(int year, StatisticsType type, double value)
        {
            StatisticsValue item = this.StatValues.Find(s => s.Year == year && s.Stat.Shortname == type.Shortname);

            if (item == null)
            {
                lock (this.StatValues) this.StatValues.Add(new StatisticsValue(year, type, value));
            }
            else
            {
                item.Value = value;
            }
        }

        #endregion

        //clears the statistics
    }
}