using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using TheAirline.Model.AirlinerModel;
using TheAirline.Model.AirportModel;
using TheAirline.Model.GeneralModel;
using TheAirline.Model.GeneralModel.Helpers;

namespace TheAirline.Model.RouteModel
{
    /*! Flight.
  * This is used for a actually flight.
  * The class needs parameter for the time table entry which the flight flights after
  */

    [Serializable]
    public class Flight : ISerializable
    {
        #region Constructors and Destructors

        public Flight(RouteTimeTableEntry entry)
        {
            Entry = entry;

            if (Entry.TimeTable.Route.Type == Route.RouteType.Passenger
                || Entry.TimeTable.Route.Type == Route.RouteType.Mixed || Entry.TimeTable.Route.Type == Route.RouteType.Helicopter)
            {
                Classes = new List<FlightAirlinerClass>();

                if (Entry != null)
                {
                    Airliner = Entry.Airliner;
                    FlightTime = MathHelpers.ConvertEntryToDate(Entry);
                    ScheduledFlightTime = FlightTime;
                }

                IsOnTime = true;
            }
            if (Entry.TimeTable.Route.Type == Route.RouteType.Cargo
                || Entry.TimeTable.Route.Type == Route.RouteType.Mixed)
            {
                if (Entry != null)
                {
                    Airliner = Entry.Airliner;
                    FlightTime = MathHelpers.ConvertEntryToDate(Entry);
                    ScheduledFlightTime = FlightTime;
                }

                IsOnTime = true;
            }

            DistanceToDestination =
                MathHelpers.GetDistance(
                    Entry.Destination.Airport.Profile.Coordinates.ConvertToGeoCoordinate(),
                    Entry.DepartureAirport.Profile.Coordinates.ConvertToGeoCoordinate());
        }

        protected Flight(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop is FieldInfo)
                    {
                        ((FieldInfo) prop).SetValue(this, entry.Value);
                    }
                    else
                    {
                        ((PropertyInfo) prop).SetValue(this, entry.Value);
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning) notSet.GetCustomAttribute(typeof (Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Public Properties

        [Versioning("airliner")]
        public FleetAirliner Airliner { get; set; }

        [Versioning("cargo")]
        public double Cargo { get; set; }

        [Versioning("classes")]
        public List<FlightAirlinerClass> Classes { get; set; }

        [Versioning("distance")]
        public double DistanceToDestination { get; set; }

        [Versioning("entry")]
        public RouteTimeTableEntry Entry { get; set; }

        public DateTime ExpectedLanding
        {
            get { return GetExpectedLandingTime(); }
        }

        [Versioning("flighttime")]
        public DateTime FlightTime { get; set; }

        [Versioning("isontime")]
        public Boolean IsOnTime { get; set; }

        [Versioning("scheduled")]
        public DateTime ScheduledFlightTime { get; set; }

        #endregion

        #region Public Methods and Operators

        public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                      .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                          .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo) member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo) member).GetValue(this, null);
                }

                var att = (Versioning) member.GetCustomAttribute(typeof (Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        //adds some delay minutes to the flight
        public virtual void AddDelayMinutes(int minutes)
        {
            FlightTime = FlightTime.AddMinutes(minutes);
        }

        //returns the scheduled expected landing time

        //returns the cargo price
        public double GetCargoPrice()
        {
            if (Entry.TimeTable.Route is CargoRoute)
                return ((CargoRoute) Entry.TimeTable.Route).PricePerUnit;
            else
                return ((CombiRoute) Entry.TimeTable.Route).PricePerUnit;
        }

        public Airport GetDepartureAirport()
        {
            return GetNextDestination();
        }

        public DateTime GetExpectedLandingTime()
        {
            return
                FlightTime.Add(
                    MathHelpers.GetFlightTime(
                        Entry.DepartureAirport.Profile.Coordinates.ConvertToGeoCoordinate(),
                        Entry.Destination.Airport.Profile.Coordinates.ConvertToGeoCoordinate(),
                        Airliner.Airliner.Type));
        }

        //returns the total number of passengers

        //returns the flight airliner class for a specific class type
        public FlightAirlinerClass GetFlightAirlinerClass(AirlinerClass.ClassType type)
        {
            return Classes.Find(c => c.AirlinerClass.Type == type);
        }

        //returns the next destination
        public Airport GetNextDestination()
        {
            return Entry.Destination.Airport == Entry.TimeTable.Route.Destination1
                       ? Entry.TimeTable.Route.Destination2
                       : Entry.TimeTable.Route.Destination1;
        }

        public DateTime GetScheduledLandingTime()
        {
            return
                ScheduledFlightTime.Add(
                    MathHelpers.GetFlightTime(
                        Entry.DepartureAirport.Profile.Coordinates.ConvertToGeoCoordinate(),
                        Entry.Destination.Airport.Profile.Coordinates.ConvertToGeoCoordinate(),
                        Airliner.Airliner.Type));
        }

        public int GetTotalPassengers()
        {
            int passengers = 0;

            foreach (FlightAirlinerClass aClass in Classes)
            {
                passengers += aClass.Passengers;
            }

            if (passengers < 0)
            {
                passengers = 0;
            }

            return passengers;
        }

        //returns the departure location

        //returns if it is a cargo flight
        public Boolean IsCargoFlight()
        {
            return Entry.TimeTable.Route.Type == Route.RouteType.Mixed
                   || Entry.TimeTable.Route.Type == Route.RouteType.Cargo;
        }

        public Boolean IsPassengerFlight()
        {
            return Entry.TimeTable.Route.Type == Route.RouteType.Mixed
                   || Entry.TimeTable.Route.Type == Route.RouteType.Passenger
                   || Entry.TimeTable.Route.Type == Route.RouteType.Helicopter;
        }

        #endregion
    }
}