
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;

namespace TheAirline.Model.GeneralModel.ScenarioModel
{
    //the class for a failure at a scenario
       [Serializable]
     public class ScenarioFailure : ISerializable
    {
        public enum FailureType { Cash, Safety, Debt, Security, Fleet, Domestic, Intl, PaxGrowth, Crime, FleetAge , Pax, Bases, JetRation}
        [Versioning("type")]
        public FailureType Type { get; set; }
        //1 - means check each month
        [Versioning("checksmonths")]
        public int CheckMonths { get; set; }
        [Versioning("value")]
        public object Value { get; set; }
        [Versioning("failuretext")]
        public string FailureText { get; set; }
        [Versioning("monthsoffailure")]
        public int MonthsOfFailure { get; set; }
        [Versioning("id")]
        public string ID { get; set; }
        public ScenarioFailure(string id, FailureType type, int checkMonths, object value, string failureText, int monthsOfFailure)
        {
            this.ID = id;
            this.Type = type;
            this.CheckMonths = checkMonths;
            this.Value = value;
            this.FailureText = failureText;
            this.MonthsOfFailure = monthsOfFailure;
        }
                private ScenarioFailure(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IList<PropertyInfo> props = new List<PropertyInfo>(this.GetType().GetProperties().Where(p => p.GetCustomAttribute(typeof(Versioning)) != null && ((Versioning)p.GetCustomAttribute(typeof(Versioning))).AutoGenerated));

            foreach (SerializationEntry entry in info)
            {
                PropertyInfo prop = props.FirstOrDefault(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Name == entry.Name);


                if (prop != null)
                    prop.SetValue(this, entry.Value);
            }

            var notSetProps = props.Where(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Version > version);

            foreach (PropertyInfo prop in notSetProps)
            {
                Versioning ver = (Versioning)prop.GetCustomAttribute(typeof(Versioning));

                if (ver.AutoGenerated)
                    prop.SetValue(this, ver.DefaultValue);

            }




        }

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = this.GetType();
            IList<PropertyInfo> props = new List<PropertyInfo>(myType.GetProperties().Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            foreach (PropertyInfo prop in props)
            {
                object propValue = prop.GetValue(this, null);

                Versioning att = (Versioning)prop.GetCustomAttribute(typeof(Versioning));

                info.AddValue(att.Name, propValue);
            }

        }
    }
   
}
