using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using TheAirline.Model.GeneralModel;
using TheAirline.Model.GeneralModel.Helpers;

namespace TheAirline.Model.AirlineModel
{
    /*! Airline Advertisement type class.
 * This class is used for a type of Advertisement for an airline
 * The class needs parameters for type, name, price per month and reputation level
 */

    [Serializable]
    public class AdvertisementType
    {
        #region Fields

        [Versioning("price")] private double _aPrice;

        #endregion

        #region Constructors and Destructors

        public AdvertisementType(AirlineAdvertisementType type, string name, double price, int reputationLevel)
        {
            Type = type;
            Name = name;
            Price = price;
            ReputationLevel = reputationLevel;
        }

        private AdvertisementType(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop is FieldInfo)
                    {
                        ((FieldInfo) prop).SetValue(this, entry.Value);
                    }
                    else
                    {
                        ((PropertyInfo) prop).SetValue(this, entry.Value);
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning) p.GetCustomAttribute(typeof (Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning) notSet.GetCustomAttribute(typeof (Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo) notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Enums

        public enum AirlineAdvertisementType
        {
            Newspaper = 1930,

            Radio = 1940,

            TV = 1950,

            Internet = 1995
        }

        #endregion

        #region Public Properties

        [Versioning("name")]
        public string Name { get; set; }

        public double Price
        {
            get { return GeneralHelpers.GetInflationPrice(_aPrice); }
            set { _aPrice = value; }
        }

        [Versioning("level")]
        public int ReputationLevel { get; set; }

        [Versioning("type")]
        public AirlineAdvertisementType Type { get; set; }

        #endregion

        #region Public Methods and Operators

        public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                      .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                          .Where(p => p.GetCustomAttribute(typeof (Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo) member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo) member).GetValue(this, null);
                }

                var att = (Versioning) member.GetCustomAttribute(typeof (Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        #endregion
    }

    /*! Airline advertisering types class.
* This class is used for the list of Advertisement types
* The class needs no parameters and construction since it is static
*/

    public class AdvertisementTypes
    {
        #region Static Fields

        private static readonly List<AdvertisementType> Advertisements = new List<AdvertisementType>();

        #endregion

        #region Public Methods and Operators

        public static void AddAdvertisementType(AdvertisementType type)
        {
            Advertisements.Add(type);
        }

        /*!clears the list of types
         */

        public static void Clear()
        {
            Advertisements.Clear();
        }

        public static AdvertisementType GetBasicType(AdvertisementType.AirlineAdvertisementType type)
        {
            return GetTypes(type).Find((delegate(AdvertisementType t) { return t.ReputationLevel == 0; }));
        }

        public static AdvertisementType GetType(AdvertisementType.AirlineAdvertisementType type, string name)
        {
            return GetTypes(type).Find((delegate(AdvertisementType t) { return t.Name == name; }));
        }

        /*!returns all advertisement types
         */

        public static List<AdvertisementType> GetTypes()
        {
            return Advertisements;
        }

        /*!returns the advertisement types for a specific type
         */

        public static List<AdvertisementType> GetTypes(AdvertisementType.AirlineAdvertisementType type)
        {
            return Advertisements.FindAll((delegate(AdvertisementType t) { return t.Type == type; }));
        }

        #endregion

        /*!adds a type to the list
         * */

        /*!returns the advertisement type for a specific type with a name
         */
    }
}