namespace TheAirline.Model.GeneralModel.InvoicesModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Runtime.Serialization;

    //the class for a collection of invoices
    [Serializable]
    public class Invoices : ISerializable
    {
        #region Constructors and Destructors

        public Invoices()
        {
            this.MonthlyInvoices = new List<MonthlyInvoice>();
        }

        private Invoices(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                this.GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    this.GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop is FieldInfo)
                    {
                        ((FieldInfo)prop).SetValue(this, entry.Value);
                    }
                    else
                    {
                        ((PropertyInfo)prop).SetValue(this, entry.Value);
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning)notSet.GetCustomAttribute(typeof(Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Public Properties

        [Versioning("invoices")]
        public List<MonthlyInvoice> MonthlyInvoices { get; set; }

        #endregion

        #region Public Methods and Operators

        public static List<double> getInvoiceList()
        {
            var invoices = new List<double>();
            foreach (MonthlyInvoice invoice in GameObject.GetInstance().HumanAirline.getInvoices().MonthlyInvoices)
            {
                invoices.Add(invoice.Amount);
            }

            return invoices;
        }

        public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = this.GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo)member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo)member).GetValue(this, null);
                }

                var att = (Versioning)member.GetCustomAttribute(typeof(Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        //adds an invoice to the invoices
        public void addInvoice(Invoice invoice)
        {
            this.addInvoice(invoice.Type, invoice.Date.Year, invoice.Date.Month, invoice.Date.Day, invoice.Amount);
        }

        public void addInvoice(Invoice.InvoiceType type, int year, int month,int day, double amount)
        {
            lock (this.MonthlyInvoices)
            {
                if (this.contains(type, year, month,day))
                {
                    MonthlyInvoice mInvoice =
                        this.MonthlyInvoices.Find(m => m.Month == month && m.Year == year && m.Type == type && m.Day == day);//optimization
                    mInvoice.Amount += amount;
                }
                else
                {
                    var mInvoice = new MonthlyInvoice(type, year, month,day, amount);
                    this.MonthlyInvoices.Add(mInvoice);
                }
            }
        }
        public Boolean contains(Invoice.InvoiceType type, int year, int month)
        {
            Boolean contains;
            lock (this.MonthlyInvoices)
            {
                contains = this.MonthlyInvoices.Exists(m => m.Month == month && m.Year == year &&  m.Type == type);
            }

            return contains;
        }

        public Boolean contains(Invoice.InvoiceType type, int year, int month, int day)
        {
            Boolean contains;
            lock (this.MonthlyInvoices)
            {
                contains = this.MonthlyInvoices.Exists(m => m.Month == month && m.Year == year && m.Day == day && m.Type == type);
            }

            return contains;
        }

        //returns the yearly amount for a given type and year

        //returns the total amount for a given type
        public double getAmount(Invoice.InvoiceType type)
        {
            return this.MonthlyInvoices.FindAll(i => i.Type == type).Sum(i => i.Amount);
        }

        //returns the total amount for a given year, month and type
        public double getAmount(Invoice.InvoiceType type, int year, int month)
        {
            if (this.contains(type, year, month))
            {

                return this.MonthlyInvoices.FindAll(m => m.Month == month && m.Year == year && m.Type == type).Sum(m => m.Amount);
            }
            return 0;
        }

        //returns the total amount for a given year and month
        public double getAmount(int year, int month)
        {
           

            return this.MonthlyInvoices.FindAll(m => m.Month == month && m.Year == year).Sum(m => m.Amount);
        }

        //returns the total amount of invoices
        public double getAmount()
        {
            double sum;
            lock (this.MonthlyInvoices)
            {
                sum = this.MonthlyInvoices.Sum(m => m.Amount);
            }
            return sum;
        }

        public double getYearlyAmount(Invoice.InvoiceType type, int year)
        {
            return this.MonthlyInvoices.FindAll(i => i.Type == type && i.Year == year).Sum(i => i.Amount);
        }

        //return the yearly amount for an year
        public double getYearlyAmount(int year)
        {
            return this.MonthlyInvoices.FindAll(i => i.Year == year).Sum(i => i.Amount);
        }

        #endregion

        //returns if the invoices contains a month, year and type element
    }
}