namespace TheAirline.Model.AirportModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Runtime.Serialization;

    using TheAirline.Model.GeneralModel;

    [Serializable]
    //the class for a facility at an airport
    public class AirportFacility : ISerializable
    {
        #region Fields

        [Versioning("price")]
        private double APrice;

        #endregion

        #region Constructors and Destructors

        public AirportFacility(
            string section,
            string uid,
            string shortname,
            FacilityType type,
            int buildingDays,
            int typeLevel,
            double price,
            int serviceLevel,
            int luxuryLevel)
        {
            Section = section;
            this.Uid = uid;
            this.Shortname = shortname;
            this.Price = price;
            this.LuxuryLevel = luxuryLevel;
            this.ServiceLevel = serviceLevel;
            this.BuildingDays = buildingDays;
            this.TypeLevel = typeLevel;
            this.Type = type;
        }

        private AirportFacility(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IEnumerable<FieldInfo> fields =
                this.GetType()
                    .GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    this.GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (SerializationEntry entry in info)
            {
                MemberInfo prop =
                    propsAndFields.FirstOrDefault(
                        p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Name == entry.Name);

                if (prop != null)
                {
                    if (prop is FieldInfo)
                    {
                        ((FieldInfo)prop).SetValue(this, entry.Value);
                    }
                    else
                    {
                        ((PropertyInfo)prop).SetValue(this, entry.Value);
                    }
                }
            }

            IEnumerable<MemberInfo> notSetProps =
                propsAndFields.Where(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Version > version);

            foreach (MemberInfo notSet in notSetProps)
            {
                var ver = (Versioning)notSet.GetCustomAttribute(typeof(Versioning));

                if (ver.AutoGenerated)
                {
                    if (notSet is FieldInfo)
                    {
                        ((FieldInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                    else
                    {
                        ((PropertyInfo)notSet).SetValue(this, ver.DefaultValue);
                    }
                }
            }
        }

        #endregion

        #region Enums

        public enum EmployeeTypes
        {
            Maintenance,

            Support
        }

        public enum FacilityType
        {
            Lounge,

            Service,

            CheckIn,

            SelfCheck,

            TicketOffice,

            Cargo
        }

        #endregion

        #region Public Properties

        public static string Section { get; set; }

        [Versioning("buildingdays")]
        public int BuildingDays { get; set; }

        [Versioning("employeetype")]
        public EmployeeTypes EmployeeType { get; set; }

        [Versioning("luxurylevel")]
        public int LuxuryLevel { get; set; }

        public virtual string Name
        {
            get
            {
                return Translator.GetInstance().GetString(Section, this.Uid);
            }
        }

        [Versioning("employees")]
        public int NumberOfEmployees { get; set; }

        public double Price
        {
            get
            {
                return GeneralHelpers.GetInflationPrice(this.APrice);
            }
            set
            {
                this.APrice = value;
            }
        }

        [Versioning("servicelevel")]
        public int ServiceLevel { get; set; }

        [Versioning("shortname")]
        public string Shortname { get; set; }

        [Versioning("type")]
        public FacilityType Type { get; set; }

        [Versioning("typelevel")]
        public int TypeLevel { get; set; }

        [Versioning("uid")]
        public string Uid { get; set; }

        #endregion

        #region Public Methods and Operators

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = this.GetType();

            IEnumerable<FieldInfo> fields =
                myType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null);

            IList<PropertyInfo> props =
                new List<PropertyInfo>(
                    myType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                        .Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            IEnumerable<MemberInfo> propsAndFields = props.Cast<MemberInfo>().Union(fields.Cast<MemberInfo>());

            foreach (MemberInfo member in propsAndFields)
            {
                object propValue;

                if (member is FieldInfo)
                {
                    propValue = ((FieldInfo)member).GetValue(this);
                }
                else
                {
                    propValue = ((PropertyInfo)member).GetValue(this, null);
                }

                var att = (Versioning)member.GetCustomAttribute(typeof(Versioning));

                info.AddValue(att.Name, propValue);
            }
        }

        #endregion
    }

    //the collection of facilities
    public class AirportFacilities
    {
        #region Static Fields

        private static Dictionary<string, AirportFacility> facilities = new Dictionary<string, AirportFacility>();

        #endregion

        //clears the list

        //adds a new facility to the collection

        #region Public Methods and Operators

        public static void AddFacility(AirportFacility facility)
        {
            facilities.Add(facility.Shortname, facility);
        }

        public static void Clear()
        {
            facilities = new Dictionary<string, AirportFacility>();
        }

        //returns a facility

        //returns the list of facilities
        public static List<AirportFacility> GetFacilities()
        {
            return facilities.Values.ToList();
        }

        //returns all facilities of a specific type
        public static List<AirportFacility> GetFacilities(AirportFacility.FacilityType type)
        {
            return GetFacilities().FindAll((delegate(AirportFacility facility) { return facility.Type == type; }));
        }

        public static AirportFacility GetFacility(string shortname)
        {
            return facilities[shortname];
        }

        #endregion
    }
}