
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;

namespace TheAirline.Model.GeneralModel
{
    /*! GameTimeZone.
* This is used for a time zone in the game
* The class needs parameters names of time zone and the utc offset
     */
    [Serializable]
    public class GameTimeZone : ISerializable
    {
        [Versioning("offset")]
        public TimeSpan UTCOffset { get; set; }
        [Versioning("shortname")]
        public string ShortName { get; set; }
        [Versioning("name")]
        public string Name { get; set; }
        public string DisplayName { get { return getDisplayName(); } set { ;} }
        public string ShortDisplayName { get { return getShortDisplayName(); } set { ;} }
        public GameTimeZone(string name, string shortName, TimeSpan utcOffset)
        {
            this.Name = name;
            this.ShortName = shortName;
            this.UTCOffset = utcOffset;
        }
        //returns the display name
        private string getDisplayName()
        {
            return string.Format("{0} (UTC{1}{2:D2}:{3:D2})", this.Name, this.UTCOffset.Hours < 0 ? "" : "+", this.UTCOffset.Hours, Math.Abs(this.UTCOffset.Minutes));
        }
        //returns the short display name
        private string getShortDisplayName()
        {
            return string.Format("{0} (UTC{1}{2:D2}:{3:D2})", this.ShortName, this.UTCOffset.Hours < 0 ? "" : "+", this.UTCOffset.Hours, Math.Abs(this.UTCOffset.Minutes));

        }
           private GameTimeZone(SerializationInfo info, StreamingContext ctxt)
        {
            int version = info.GetInt16("version");

            IList<PropertyInfo> props = new List<PropertyInfo>(this.GetType().GetProperties().Where(p => p.GetCustomAttribute(typeof(Versioning)) != null && ((Versioning)p.GetCustomAttribute(typeof(Versioning))).AutoGenerated));

            foreach (SerializationEntry entry in info)
            {
                PropertyInfo prop = props.FirstOrDefault(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Name == entry.Name);


                if (prop != null)
                    prop.SetValue(this, entry.Value);
            }

            var notSetProps = props.Where(p => ((Versioning)p.GetCustomAttribute(typeof(Versioning))).Version > version);

            foreach (PropertyInfo prop in notSetProps)
            {
                Versioning ver = (Versioning)prop.GetCustomAttribute(typeof(Versioning));

                if (ver.AutoGenerated)
                    prop.SetValue(this, ver.DefaultValue);

            }




        }

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("version", 1);

            Type myType = this.GetType();
            IList<PropertyInfo> props = new List<PropertyInfo>(myType.GetProperties().Where(p => p.GetCustomAttribute(typeof(Versioning)) != null));

            foreach (PropertyInfo prop in props)
            {
                object propValue = prop.GetValue(this, null);

                Versioning att = (Versioning)prop.GetCustomAttribute(typeof(Versioning));

                info.AddValue(att.Name, propValue);
            }

        }
    }
    //the list of time zones
    public class TimeZones
    {
       
        private static List<GameTimeZone> timeZones = new List<GameTimeZone>();
        //clears the list
        public static void Clear()
        {
            timeZones.Clear();
        }
        //adds a time zone to the list
        public static void AddTimeZone(GameTimeZone tz)
        {
            timeZones.Add(tz);
        }
        //returns the list of time zones
        public static List<GameTimeZone> GetTimeZones()
        {
            return timeZones;
        }
      
    }
}
