namespace TheAirline.Model.GeneralModel
{
    using System;

    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field)]
    public class Versioning : Attribute
    {
        #region Fields

        private readonly string name;

        #endregion

        #region Constructors and Destructors

        public Versioning(string name)
        {
            this.name = name;
            this.Version = 1;
            this.AutoGenerated = true;
        }

        #endregion

        // This property is readonly (it has no set accessor)
        // so it cannot be used as a named argument to this attribute.

        #region Public Properties

        public bool AutoGenerated { get; set; }

        public object DefaultValue { get; set; }

        public string Name
        {
            get
            {
                return this.name;
            }
        }

        public double Version { get; set; }

        #endregion
    }
}